name: OIDC Workflow

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::828562155228:role/github-actions-ecr-role
          aws-region: us-east-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2